name: flutter_pdf_generator
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/vlado-rudenok/flutter_pdf_generator

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.vlqdo.flutter_pdf_generator
        pluginClass: FlutterPdfGeneratorPlugin
      ios:
        pluginClass: FlutterPdfGeneratorPlugin
